"""initial

Revision ID: 5fda02050404
Revises: 
Create Date: 2026-05-30 19:41:50.656400
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5fda02050404'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('layer_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_processed', sa.Integer(), nullable=True),
    sa.Column('tokens_passed', sa.Integer(), nullable=True),
    sa.Column('tokens_rejected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('contract_address', sa.String(length=128), nullable=False),
    sa.Column('pair_address', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('dex_id', sa.String(length=64), nullable=True),
    sa.Column('age_bucket', sa.Enum('NEW_LAUNCH', 'YOUNG', 'GROWING', 'MATURE', name='agebucket'), nullable=True),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_status', sa.Enum('DISCOVERED', 'IDENTITY_RESOLVED', 'AGE_CLASSIFIED', 'SAFETY_PASSED', 'MANIPULATION_CHECKED', 'ATTENTION_SCORED', 'MARKET_FLOW_SCORED', 'ADOPTION_SCORED', 'LIQUIDITY_SCORED', 'SMART_MONEY_SCORED', 'NARRATIVE_SCORED', 'PRICE_COMPRESSION_SCORED', 'RISK_SCORED', 'MOMENTUM_SCORED', 'RANKED', 'HUMAN_REVIEWED', 'VALIDATED', 'REJECTED', name='pipelinestatus'), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_honeypot', sa.Boolean(), nullable=True),
    sa.Column('has_mint_risk', sa.Boolean(), nullable=True),
    sa.Column('has_sell_block', sa.Boolean(), nullable=True),
    sa.Column('is_liquidity_locked', sa.Boolean(), nullable=True),
    sa.Column('buy_tax_pct', sa.Float(), nullable=True),
    sa.Column('sell_tax_pct', sa.Float(), nullable=True),
    sa.Column('liquidity_usd', sa.Float(), nullable=True),
    sa.Column('liquidity_trend', sa.String(length=16), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('volume_1h', sa.Float(), nullable=True),
    sa.Column('trade_count_24h', sa.Integer(), nullable=True),
    sa.Column('unique_buyers_24h', sa.Integer(), nullable=True),
    sa.Column('unique_sellers_24h', sa.Integer(), nullable=True),
    sa.Column('holder_count', sa.Integer(), nullable=True),
    sa.Column('meaningful_holders', sa.Integer(), nullable=True),
    sa.Column('top_holder_pct', sa.Float(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('price_change_1h', sa.Float(), nullable=True),
    sa.Column('price_change_6h', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_7d', sa.Float(), nullable=True),
    sa.Column('distance_from_24h_high', sa.Float(), nullable=True),
    sa.Column('distance_from_7d_high', sa.Float(), nullable=True),
    sa.Column('distance_from_30d_high', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('fully_diluted_valuation', sa.Float(), nullable=True),
    sa.Column('attention_score', sa.Float(), nullable=True),
    sa.Column('market_flow_score', sa.Float(), nullable=True),
    sa.Column('adoption_score', sa.Float(), nullable=True),
    sa.Column('liquidity_quality_score', sa.Float(), nullable=True),
    sa.Column('smart_money_score', sa.Float(), nullable=True),
    sa.Column('narrative_score', sa.Float(), nullable=True),
    sa.Column('price_compression_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('early_momentum_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.Enum('TIER_A', 'TIER_B', 'TIER_C', 'EXCLUDED', name='rankingtier'), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('docs_url', sa.String(length=512), nullable=True),
    sa.Column('team_info', sa.JSON(), nullable=True),
    sa.Column('roadmap_summary', sa.Text(), nullable=True),
    sa.Column('tokenomics_summary', sa.Text(), nullable=True),
    sa.Column('human_review_notes', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('coingecko_trending', sa.Boolean(), nullable=True),
    sa.Column('cmc_trending', sa.Boolean(), nullable=True),
    sa.Column('news_mentions', sa.Integer(), nullable=True),
    sa.Column('exchange_listings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'contract_address', name='uq_token_chain_contract')
    )
    op.create_index('ix_token_momentum', 'tokens', ['early_momentum_score'], unique=False)
    op.create_index('ix_token_pair', 'tokens', ['chain', 'pair_address'], unique=False)
    op.create_index('ix_token_tier', 'tokens', ['tier'], unique=False)
    op.create_index(op.f('ix_tokens_chain'), 'tokens', ['chain'], unique=False)
    op.create_index(op.f('ix_tokens_contract_address'), 'tokens', ['contract_address'], unique=False)
    op.create_index(op.f('ix_tokens_pair_address'), 'tokens', ['pair_address'], unique=False)
    op.create_table('discovery_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('DEXSCREENER_VOLUME', 'DEXSCREENER_TRENDING', 'TWITTER', 'TELEGRAM', 'REDDIT', 'SMART_WALLET', 'DORMANT_AWAKENING', 'NARRATIVE', name='discoverysource'), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_events_token_id'), 'discovery_events', ['token_id'], unique=False)
    op.create_table('holder_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('total_holders', sa.Integer(), nullable=True),
    sa.Column('meaningful_holders', sa.Integer(), nullable=True),
    sa.Column('active_wallets', sa.Integer(), nullable=True),
    sa.Column('new_wallets_6h', sa.Integer(), nullable=True),
    sa.Column('suspected_bot_wallets', sa.Integer(), nullable=True),
    sa.Column('top_10_share_pct', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holder_snapshots_token_id'), 'holder_snapshots', ['token_id'], unique=False)
    op.create_table('manipulation_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manipulation_flags_token_id'), 'manipulation_flags', ['token_id'], unique=False)
    op.create_table('smart_wallet_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('buy_amount_usd', sa.Float(), nullable=True),
    sa.Column('wallet_avg_buy_size', sa.Float(), nullable=True),
    sa.Column('normalized_buy_size', sa.Float(), nullable=True),
    sa.Column('wallet_win_rate', sa.Float(), nullable=True),
    sa.Column('wallet_avg_roi', sa.Float(), nullable=True),
    sa.Column('wallet_completed_trades', sa.Integer(), nullable=True),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_wallet_trades_token_id'), 'smart_wallet_trades', ['token_id'], unique=False)
    op.create_index(op.f('ix_smart_wallet_trades_wallet_address'), 'smart_wallet_trades', ['wallet_address'], unique=False)
    op.create_table('social_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('unique_accounts', sa.Integer(), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=True),
    sa.Column('new_members', sa.Integer(), nullable=True),
    sa.Column('is_spam_flagged', sa.Boolean(), nullable=True),
    sa.Column('spam_reason', sa.String(length=256), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_mentions_token_id'), 'social_mentions', ['token_id'], unique=False)
    op.create_index('ix_social_source_time', 'social_mentions', ['token_id', 'source', 'snapshot_at'], unique=False)
    op.create_table('token_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('avg_volume_15m', sa.Float(), nullable=True),
    sa.Column('avg_volume_1h', sa.Float(), nullable=True),
    sa.Column('avg_volume_6h', sa.Float(), nullable=True),
    sa.Column('avg_volume_24h', sa.Float(), nullable=True),
    sa.Column('avg_volume_7d', sa.Float(), nullable=True),
    sa.Column('avg_volume_30d', sa.Float(), nullable=True),
    sa.Column('avg_volume_90d', sa.Float(), nullable=True),
    sa.Column('avg_trades_1h', sa.Float(), nullable=True),
    sa.Column('avg_trades_6h', sa.Float(), nullable=True),
    sa.Column('avg_trades_24h', sa.Float(), nullable=True),
    sa.Column('avg_twitter_mentions', sa.Float(), nullable=True),
    sa.Column('avg_telegram_messages', sa.Float(), nullable=True),
    sa.Column('avg_reddit_mentions', sa.Float(), nullable=True),
    sa.Column('avg_new_holders_6h', sa.Float(), nullable=True),
    sa.Column('avg_new_holders_24h', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_table('token_narratives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('narrative', sa.Enum('AI', 'RWA', 'DEPIN', 'GAMING', 'PRIVACY', 'MEMES', 'PREDICTION_MARKETS', 'L1_L2', name='narrativetype'), nullable=False),
    sa.Column('strength', sa.Enum('COLD', 'WARM', 'HOT', 'DOMINANT', name='narrativestrength'), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'narrative', name='uq_token_narrative')
    )
    op.create_index(op.f('ix_token_narratives_token_id'), 'token_narratives', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_narratives_token_id'), table_name='token_narratives')
    op.drop_table('token_narratives')
    op.drop_table('token_baselines')
    op.drop_index('ix_social_source_time', table_name='social_mentions')
    op.drop_index(op.f('ix_social_mentions_token_id'), table_name='social_mentions')
    op.drop_table('social_mentions')
    op.drop_index(op.f('ix_smart_wallet_trades_wallet_address'), table_name='smart_wallet_trades')
    op.drop_index(op.f('ix_smart_wallet_trades_token_id'), table_name='smart_wallet_trades')
    op.drop_table('smart_wallet_trades')
    op.drop_index(op.f('ix_manipulation_flags_token_id'), table_name='manipulation_flags')
    op.drop_table('manipulation_flags')
    op.drop_index(op.f('ix_holder_snapshots_token_id'), table_name='holder_snapshots')
    op.drop_table('holder_snapshots')
    op.drop_index(op.f('ix_discovery_events_token_id'), table_name='discovery_events')
    op.drop_table('discovery_events')
    op.drop_index(op.f('ix_tokens_pair_address'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_contract_address'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_chain'), table_name='tokens')
    op.drop_index('ix_token_tier', table_name='tokens')
    op.drop_index('ix_token_pair', table_name='tokens')
    op.drop_index('ix_token_momentum', table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
