"""gmgn_dexscreener_discovery_tables

Revision ID: f46e205749d7
Revises: 8e1bbd154960
Create Date: 2026-06-06 15:48:49.699058
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f46e205749d7'
down_revision: Union[str, None] = '8e1bbd154960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_twitter_candidate_tokens_chain', table_name='twitter_candidate_tokens')
    op.drop_index('ix_twitter_candidate_tokens_token_address', table_name='twitter_candidate_tokens')
    op.drop_table('twitter_candidate_tokens')
    op.drop_index('ix_twitter_tweets_text_hash', table_name='twitter_tweets')
    op.drop_index('ix_twitter_tweets_timestamp', table_name='twitter_tweets')
    op.drop_table('twitter_tweets')
    op.drop_index('ix_twitter_mentions_candidate_token_id', table_name='twitter_token_mentions')
    op.drop_index('ix_twitter_mentions_source_id', table_name='twitter_token_mentions')
    op.drop_index('ix_twitter_mentions_timestamp', table_name='twitter_token_mentions')
    op.drop_index('ix_twitter_mentions_token_window', table_name='twitter_token_mentions')
    op.drop_index('ix_twitter_mentions_tweet_id', table_name='twitter_token_mentions')
    op.drop_table('twitter_token_mentions')
    op.drop_index('ix_twitter_sources_enabled', table_name='twitter_sources')
    op.drop_index('ix_twitter_sources_source_id', table_name='twitter_sources')
    op.drop_table('twitter_sources')
    op.drop_index('ix_twitter_rankings_candidate_token_id', table_name='twitter_discovery_rankings')
    op.drop_index('ix_twitter_rankings_token_window', table_name='twitter_discovery_rankings')
    op.drop_index('ix_twitter_rankings_window', table_name='twitter_discovery_rankings')
    op.drop_table('twitter_discovery_rankings')
    op.alter_column('candidate_tokens', 'gmgn_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('candidate_tokens', 'dexscreener_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('candidate_tokens', 'ai_evaluation',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_constraint('reddit_sources_source_id_key', 'reddit_sources', type_='unique')
    op.drop_index('ix_reddit_sources_source_id', table_name='reddit_sources')
    op.create_index(op.f('ix_reddit_sources_source_id'), 'reddit_sources', ['source_id'], unique=True)
    op.alter_column('telegram_messages', 'reactions_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_messages', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_messages', 'forwards_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_messages', 'reply_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint('telegram_sources_source_id_key', 'telegram_sources', type_='unique')
    op.drop_index('ix_telegram_sources_source_id', table_name='telegram_sources')
    op.create_index(op.f('ix_telegram_sources_source_id'), 'telegram_sources', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_sources_source_id'), table_name='telegram_sources')
    op.create_index('ix_telegram_sources_source_id', 'telegram_sources', ['source_id'], unique=False)
    op.create_unique_constraint('telegram_sources_source_id_key', 'telegram_sources', ['source_id'])
    op.alter_column('telegram_messages', 'reply_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_messages', 'forwards_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_messages', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_messages', 'reactions_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_reddit_sources_source_id'), table_name='reddit_sources')
    op.create_index('ix_reddit_sources_source_id', 'reddit_sources', ['source_id'], unique=False)
    op.create_unique_constraint('reddit_sources_source_id_key', 'reddit_sources', ['source_id'])
    op.alter_column('candidate_tokens', 'ai_evaluation',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('candidate_tokens', 'dexscreener_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('candidate_tokens', 'gmgn_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_table('twitter_discovery_rankings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('mention_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unique_user_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_engagement', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('authority_mentions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_token_id'], ['twitter_candidate_tokens.id'], name='twitter_discovery_rankings_candidate_token_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='twitter_discovery_rankings_pkey')
    )
    op.create_index('ix_twitter_rankings_window', 'twitter_discovery_rankings', ['window_start', 'window_end'], unique=False)
    op.create_index('ix_twitter_rankings_token_window', 'twitter_discovery_rankings', ['candidate_token_id', 'window_start'], unique=False)
    op.create_index('ix_twitter_rankings_candidate_token_id', 'twitter_discovery_rankings', ['candidate_token_id'], unique=False)
    op.create_table('twitter_sources',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('source_type', postgresql.ENUM('CASHTAG_SEARCH', 'KEYWORD_SEARCH', 'ADDRESS_SEARCH', 'ACCOUNT_MONITOR', name='twittersourcetype'), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('last_tweet_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('last_collected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='twitter_sources_pkey'),
    sa.UniqueConstraint('source_id', name='twitter_sources_source_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_twitter_sources_source_id', 'twitter_sources', ['source_id'], unique=False)
    op.create_index('ix_twitter_sources_enabled', 'twitter_sources', ['enabled'], unique=False)
    op.create_table('twitter_token_mentions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_token_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tweet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tweet_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('discovery_method', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_reputable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('engagement_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_token_id'], ['twitter_candidate_tokens.id'], name='twitter_token_mentions_candidate_token_id_fkey'),
    sa.ForeignKeyConstraint(['source_id'], ['twitter_sources.id'], name='twitter_token_mentions_source_id_fkey'),
    sa.ForeignKeyConstraint(['tweet_id'], ['twitter_tweets.id'], name='twitter_token_mentions_tweet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='twitter_token_mentions_pkey'),
    sa.UniqueConstraint('candidate_token_id', 'tweet_id', 'discovery_method', name='uq_twitter_mention_token_tweet_method')
    )
    op.create_index('ix_twitter_mentions_tweet_id', 'twitter_token_mentions', ['tweet_id'], unique=False)
    op.create_index('ix_twitter_mentions_token_window', 'twitter_token_mentions', ['candidate_token_id', 'tweet_timestamp'], unique=False)
    op.create_index('ix_twitter_mentions_timestamp', 'twitter_token_mentions', ['tweet_timestamp'], unique=False)
    op.create_index('ix_twitter_mentions_source_id', 'twitter_token_mentions', ['source_id'], unique=False)
    op.create_index('ix_twitter_mentions_candidate_token_id', 'twitter_token_mentions', ['candidate_token_id'], unique=False)
    op.create_table('twitter_tweets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tweet_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tweet_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('text_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('tweet_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retweet_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('like_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('reply_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('tweet_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['twitter_sources.id'], name='twitter_tweets_source_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='twitter_tweets_pkey'),
    sa.UniqueConstraint('source_id', 'tweet_id', name='uq_twitter_tweet_source_tweetid')
    )
    op.create_index('ix_twitter_tweets_timestamp', 'twitter_tweets', ['tweet_timestamp'], unique=False)
    op.create_index('ix_twitter_tweets_text_hash', 'twitter_tweets', ['text_hash'], unique=False)
    op.create_table('twitter_candidate_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chain', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('token_address', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('first_discovered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('first_discovered_source_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_discovery_method', postgresql.ENUM('CASHTAG', 'CONTRACT_ADDRESS', 'TOKEN_NAME', name='twitterdiscoverymethod'), autoincrement=False, nullable=False),
    sa.Column('pair_address', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('dex_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['first_discovered_source_id'], ['twitter_sources.id'], name='twitter_candidate_tokens_first_discovered_source_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='twitter_candidate_tokens_pkey'),
    sa.UniqueConstraint('chain', 'token_address', name='uq_twitter_candidate_token_chain_address')
    )
    op.create_index('ix_twitter_candidate_tokens_token_address', 'twitter_candidate_tokens', ['token_address'], unique=False)
    op.create_index('ix_twitter_candidate_tokens_chain', 'twitter_candidate_tokens', ['chain'], unique=False)
    # ### end Alembic commands ###
